# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Teamhero < Formula
  desc "Developer contribution report generator with interactive TUI"
  homepage "https://github.com/asabaylus/teamhero.scripts"
  version "0.2.0-rc.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asabaylus/teamhero.scripts/releases/download/v0.2.0-rc.2/teamhero-v0.2.0-rc.2-darwin-amd64.tar.gz"
      sha256 "91454ac5f687b4dfd3dca61fa3a14e9af1236d546e55baf05acdfc3a48c09095"

      define_method(:install) do
        bin.install "teamhero-tui" => "teamhero"
        bin.install "teamhero-service" if File.exist?("teamhero-service")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asabaylus/teamhero.scripts/releases/download/v0.2.0-rc.2/teamhero-v0.2.0-rc.2-darwin-arm64.tar.gz"
      sha256 "cd1b23f8be55b91765f39d15073b68fe614b782ae146983596088ebcc1faacff"

      define_method(:install) do
        bin.install "teamhero-tui" => "teamhero"
        bin.install "teamhero-service" if File.exist?("teamhero-service")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asabaylus/teamhero.scripts/releases/download/v0.2.0-rc.2/teamhero-v0.2.0-rc.2-linux-amd64.tar.gz"
      sha256 "34d7e897e346d403cf362524e458792e44e4885cdab369b92433bb20df7fec3f"
      define_method(:install) do
        bin.install "teamhero-tui" => "teamhero"
        bin.install "teamhero-service" if File.exist?("teamhero-service")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asabaylus/teamhero.scripts/releases/download/v0.2.0-rc.2/teamhero-v0.2.0-rc.2-linux-arm64.tar.gz"
      sha256 "5fd7116229897e2c2ad003d41f51673cdfa94a7c350f88ed64064df5da60594f"
      define_method(:install) do
        bin.install "teamhero-tui" => "teamhero"
        bin.install "teamhero-service" if File.exist?("teamhero-service")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/teamhero --version")
  end
end
