# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Teamhero < Formula
  desc "Developer contribution report generator with interactive TUI"
  homepage "https://github.com/asabaylus/teamhero.cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/asabaylus/teamhero.cli/releases/download/v0.2.0/teamhero-v0.2.0-darwin-amd64.tar.gz"
      sha256 "7191dc945980fba3e0d554b09bd749ced1b70a3afee6399939160b94899bf1b9"

      define_method(:install) do
        bin.install "teamhero-tui" => "teamhero"
        bin.install "teamhero-service" if File.exist?("teamhero-service")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/asabaylus/teamhero.cli/releases/download/v0.2.0/teamhero-v0.2.0-darwin-arm64.tar.gz"
      sha256 "7d5d177900ae375f54a78fe80cb2660e866225b41af656daf2d78bdc0228eb66"

      define_method(:install) do
        bin.install "teamhero-tui" => "teamhero"
        bin.install "teamhero-service" if File.exist?("teamhero-service")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/asabaylus/teamhero.cli/releases/download/v0.2.0/teamhero-v0.2.0-linux-amd64.tar.gz"
      sha256 "b0b43688deb0b065da186b0727c5b275c61a492b5199e4d4921710fc03921cd4"
      define_method(:install) do
        bin.install "teamhero-tui" => "teamhero"
        bin.install "teamhero-service" if File.exist?("teamhero-service")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/asabaylus/teamhero.cli/releases/download/v0.2.0/teamhero-v0.2.0-linux-arm64.tar.gz"
      sha256 "eed98b19a7fee3a0f6e66b43aee6baae123f0e4304fad5de1ce59ac838ea6a24"
      define_method(:install) do
        bin.install "teamhero-tui" => "teamhero"
        bin.install "teamhero-service" if File.exist?("teamhero-service")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/teamhero --version")
  end
end
